name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸŸ¢ Usage Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: ðŸ“¦ Install Dependencies
        run: npm ci

      - name: ðŸ›  Build Project
        run: npm run build

      - name: ðŸ“‚ Sync files (SFTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          protocol: sftp
          port: 22
          security: loose
          log-level: verbose
          local-dir: ./dist/
          server-dir: ${{ secrets.REMOTE_TARGET }}
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/node_modules/**
            api/config.php
            public/api/config.php
